server:
  port: 8070

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/dnw
    username: root
    password: 1234
  config:
    import: classpath:application-secret.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/




